project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://yahaiz.github.io/blog/
  title: "Yahya Izadi"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/yahya-izadi/
        target: _blank
      - icon: github
        text: Github
        href: https://github.com/yahaiz
        target: _blank
format:
  html:
    theme:
      light: Cosmo
      dark: Superhero




